[package]
name = "scrap"
version = "0.1.0"
authors = ["Shady Khalifa <shekohex@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.10", default-features = false, features = ["rustls-tls"] }