[package]
name = "adder-ffi"
version = "0.1.0"
authors = [""]
edition = "2018"

[lib]
name = "adder_ffi"
crate-type = ["rlib"]

[dependencies]
adder = { path = "../adder" }

[build-dependencies]
cbindgen = "0.14.3"
dart-bindgen = "^0.1.8"