name: adder
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  ffi: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  ffigen: ^4.1.0

flutter:
  plugin:
    androidPackage: com.example.adder
    pluginClass: AdderPlugin

ffigen:
  output: "lib/ffi1.dart"
  headers:
    entry-points:
      - "../../native/adder-ffi/binding.h"